name: Update GitHub Profile Stats

on:
  
  workflow_dispatch:  # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with latest stats
        run: |
          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=shuklaShubhendu&theme=highcontrast" -o streak-stats.png
          curl -s "https://github-readme-stats.vercel.app/api?username=shuklaShubhendu&show_icons=true&theme=radical" -o github-stats.png
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add streak-stats.png github-stats.png
          git commit -m "Update GitHub stats images"
          git push
